name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/check@v3

      - name: Install Elm
        run: |
          curl -L -o elm.gz https://github.com/elm/compiler/releases/download/0.19.1/binary-for-linux-64-bit.gz
          gunzip elm.gz
          chmod +x elm
          sudo mv elm /usr/local/bin

      - name: Install Dependencies
        run: elm install

      - name: Build Project
        run: elm make src/Main.elm

      - name: Move to build
        run: mkdir public && mv index.html public/index.html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          user_name: ethanppl
          user_email: 43922849+ethanppl@users.noreply.github.com
